- id: unicornA_base1_all
  desc: all logs from unicornA
  code:
    - rosstream2boot.MultiLog
    - logs: 
      - 'unicornA_base1_2013-04-*'

- id: unicornA_base1_2013-04-02-20-37-43
  desc: long log
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-02-20-37-43.bag
        "file:outside": unicornA_base1_2013-04-02-20-37-43.outside.mp4
      annotations:
        robot: &unicornA_base1
          name: unicorn
          shape: unicornA
          profile: base1
        motion:
          agent: babbler
        environment: &lab_boxes3
          name: lab
          config: boxes3
        events:
          disturbances: []
        notes: |
          video: 2013-04-02 21_44_16 (id).mov 11.3 GB 37 min
          babbler: --frequency=1 --min_length=3 --max_length=10 --levy=1 
          status: Finished “active” after crash but ok
        use_for_learning: true
  
- id: unicornA_base1_2013-04-03-12-58-11
  desc: ""
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-03-12-58-11.bag
      annotations:
        robot: *unicornA_base1
        environment: *lab_boxes3
        events:
          disturbances: []
        use_for_learning: true
        notes: |
          2013-04-03 14_04_46 (id).mov 17 min
          babbler:--frequency=1 --min_length=10 --max_length=30 --levy=1
          status: short, not sure why it stopped

- id: unicornA_base1_2013-04-03-13-16-53
  desc: ""
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-03-13-16-53.bag
      annotations:
        robot: *unicornA_base1
        environment: *lab_boxes3
        events:
          disturbances: []
        use_for_learning: False
        disturbance: 
        - type: crash
          time: 000 # XXX  
        notes: |
          2013-04-03 14_23_23 (id).mov  7 min
          babbler: --frequency=1 --min_length=10 --max_length=30 --levy=1
          crashes into curtains

- id: unicornA_base1_2013-04-03-13-30-28
  desc: ""
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-03-13-30-28.bag
      annotations:
        robot: *unicornA_base1
        environment: *lab_boxes3
        events:
          disturbances: []
        use_for_learning: true
        disturbance: []
        notes: |
          2013-04-03 14_37_13 (id).mov   38 min
          Changed: warn_distance=0.65 (from 0.55); ignore_closer=0.35 (from 0.4)
          babbler: --frequency=1 --min_length=10 --max_length=30 --levy=1

- id: unicornA_base1_2013-04-03-16-36-03
  desc: ""
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-03-16-36-03.bag
      annotations:
        robot: *unicornA_base1
        environment: *lab_boxes3
        events:
          disturbances: []
        use_for_learning: true
        disturbance: []
        notes: |
          2013-04-03 17_43_05 (id).mov   16:53
          canon camera  starts a bit late (1 second or so)
          status: ends for under voltag

- id: unicornA_base1_2013-04-06-15-30-06
  desc: "6min"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-06-15-30-06.bag
      annotations:
        robot: *unicornA_base1
        environment: *lab_boxes3
        events:
          disturbances: []
        use_for_learning: true
        disturbance: []
        notes: |
          original video: 2013-04-06 14_31_36 (id).mov
    
- id: unicornA_base1_2013-04-06-19-44-59
  desc: "6min"
  code:
    - rosstream2boot.ExpLogFromYaml
    - files:
        "file:bag": ~/01-youbot-ros-logs-good/unicornA_base1_2013-04-06-19-44-59.bag
      annotations:
        robot: *unicornA_base1
        environment: *lab_boxes3
        events:
          disturbances: []
        use_for_learning: true
        notes: |
          disturbance: ['people'] 
        notes: |
          no video available -- camera battery died
    

