# hr: hokuyo right
# hl: hokuyo left
# cf: camera front (actually cam_back in the ROS conf)
# cr: camera right eye

# - id: unicornA_base1_hl
# - id: unicornA_base1_hr
# - id: unicornA_base1_hlhr
# scan1='/scan_hokuyo_H1204906'
# scan2='/scan_hokuyo_H1205005'
# cam1='/cam_eye_right/image_raw/compressed'
# cam2='/cam_back/image_raw/compressed'

- id: unicornA_base1_tw_cf
  desc: Only front camera
  code:
  - rosstream2boot.ROSRobotAdapter_from_yaml
  - obs_adapter: unicornA_cf_320
    cmd_adapter: twist_1_1

# - id: unicornA_base1_crcf
# - id: unicornA_base1_crcfhrhl